input-files:
  - "${.}/template/README-header.md"
  - "${.}/0. Introduction.md"
  - "${.}/1. Vehicle Language.md"
  - "${.}/template/README-footer.md"

filters:
  - type: citeproc

metadata:
  bibliography: "bibliography.bib"
