"""Sequential property-driven training of one ACAS Xu network on the ten Reluplex properties.

Ten epochs, one property per epoch: epoch k trains on specs/propertyKK.vcl only, starting
from the network saved at the end of epoch k-1 (epoch 1 starts from the original ONNX
file). A snapshot is saved after every epoch. With --cycles C the ten-property tour is
repeated C times (10*C epochs; epoch e trains on property ((e-1) mod 10) + 1). Everything else follows pdt-acas.py (the first round's script, kept in this folder),
which is chapter-code/capucci-pdt/pdt-Capucci-v028.py adapted to ACAS Xu:

  * no task loss (ALPHA = 0): there is no ACAS Xu data set, so the objective is the
    compiled property loss and nothing else;
  * an epoch is STEPS_PER_EPOCH = 16 gradient steps, each on one evaluation of the compiled
    loss (Vehicle's adversarial search: 10 random starts, 5 PGD steps, over the region the
    property quantifies over);
  * Capucci `qllAdditive` logic (p is set when the specs are generated by split-spec.py);
  * Adam at lr 1e-3, one optimiser kept across all epochs; no gradient clipping unless
    --clip is given (the unbounded Capucci loss diverged to NaN in the second tour of the
    three-cycle run without it).

After every epoch ALL ten property losses are evaluated on the current network (no
gradient), so traces/NET_loss_matrix.csv shows how training on property k moves every
other property. Verification is done separately by verify-acas2.py against the unchanged
upstream specification.

Compilation runs the `vehicle` CLI in a subprocess (one call per spec) rather than the
in-process compiler, because the in-process compiler was seen to return empty output on
a second call within one Python process.

Usage (from this folder):

    python3 pdt-acas2.py                # network 1_7, ten epochs
    python3 pdt-acas2.py 1_8
    python3 pdt-acas2.py 1_8 --cycles 3 --tag cyc3     # three tours, 30 epochs (diverged, see README)
    python3 pdt-acas2.py 1_8 --cycles 3 --clip 1.0 --tag cyc3clip   # the same with gradient clipping (also diverged)
    python3 pdt-acas2.py 1_8 --cycles 3 --reset-adam --tag cyc3reset  # fresh Adam each epoch
    python3 pdt-acas2.py --check        # only compile the ten specs and print the losses
                                        # and gradient norms on the starting network

Outputs (NET = the network id):

    models/acasXu_NET_seq_e00.onnx      the starting network re-exported
    models/acasXu_NET_seq_eKK.onnx      after epoch KK (trained on property KK)
    traces/NET_TAG_per_epoch.csv        epoch, property, loss mean/last, agreement, seconds
    traces/NET_TAG_steps.csv            one row per gradient step
    traces/NET_TAG_loss_matrix.csv      epoch x property: all ten losses after each epoch
"""

import argparse
import csv
import json
import os
import subprocess
import sys
import time
from collections import defaultdict

import numpy as np
import onnx
import torch
import torch.nn as nn
from onnx import numpy_helper

from vehicle_lang._ast import _nodes
from vehicle_lang.loss._pytorch._translation import PyTorchTranslation
from vehicle_lang.loss.pytorch import DefaultPyTorchSampler

torch.set_num_threads(4)

HERE = os.path.dirname(os.path.abspath(__file__))
SPECS = [os.path.join(HERE, "specs", f"property{k:02d}.vcl") for k in range(1, 11)]
LOGIC = "qllAdditive"

STEPS_PER_EPOCH = 16
LEARNING_RATE = 1e-3
ALPHA = 0.0
SEED = 0
N_MONITOR = 20_000

# Constants of the upstream specification, for the agreement proxy only.
PI = 3.141592
MIN_IN = torch.tensor([0.0, -PI, -PI, 100.0, 0.0])
MAX_IN = torch.tensor([60261.0, PI, PI, 1200.0, 1200.0])
MEAN_IN = torch.tensor([19791.091, 0.0, 0.0, 650.0, 600.0])


def log(message):
    print(f"[{time.strftime('%H:%M:%S')}] {message}", flush=True)


def normalise(x):
    return (x - MEAN_IN) / (MAX_IN - MIN_IN)


# --- network reload / export, as in pdt-acas.py -------------------------------
def load_network(path):
    weights = {i.name: numpy_helper.to_array(i) for i in onnx.load(path).graph.initializer}
    assert not weights["input_AvgImg"].any(), "expected the ONNX Sub to subtract zeros"
    names = [f"Operation_{k}" for k in range(1, 7)] + ["linear_7"]
    layers = []
    for k, name in enumerate(names):
        W = torch.tensor(weights[f"{name}_MatMul_W"].T.copy())
        b = torch.tensor(weights[f"{name}_Add_B"])
        linear = nn.Linear(W.shape[1], W.shape[0])
        linear.weight.data = W
        linear.bias.data = b
        layers.append(linear)
        if k < len(names) - 1:
            layers.append(nn.ReLU())
    return nn.Sequential(*layers)


def check_against_onnxruntime(model, path):
    try:
        import onnxruntime as ort
    except ImportError:
        log("onnxruntime not installed; skipping the reload check")
        return
    session = ort.InferenceSession(path)
    probe = (torch.rand(256, 5) * 2 - 1).numpy().astype(np.float32)
    ours = model(torch.tensor(probe)).detach().numpy()
    theirs = np.concatenate(
        [session.run(None, {"input": p.reshape(1, 1, 1, 5)})[0].reshape(1, 5) for p in probe]
    )
    deviation = float(np.abs(ours - theirs).max())
    assert deviation < 1e-4, f"reloaded network deviates from {path} by {deviation}"
    log(f"reloaded weights agree with onnxruntime on 256 probes (max deviation {deviation:.1e})")


def export(model, dst):
    was_training = model.training
    model.eval()
    torch.onnx.export(model, torch.randn(1, 5), dst + ".part",
                      input_names=["input"], output_names=["output"], external_data=False)
    os.replace(dst + ".part", dst)
    if was_training:
        model.train()


# --- compiling a specification to a loss, via the CLI ----------------------------------
def compile_loss(spec_path, property_name):
    command = ["vehicle", "--json", "compile", "loss", "--logic", LOGIC, f"--specification={spec_path}"]
    proc = subprocess.run(command, capture_output=True, text=True, cwd=HERE)
    if proc.returncode != 0 or not proc.stdout.strip():
        raise RuntimeError(f"{' '.join(command)} failed:\n{proc.stderr}")
    program = _nodes.Program.from_json(proc.stdout)
    sampler = DefaultPyTorchSampler()
    compiled = PyTorchTranslation().compile(
        program=program, path=spec_path, declaration_context={},
        samplers=defaultdict(lambda: sampler.get_loss),
    )
    return compiled[property_name]


def loss_value(loss_fn, network):
    return torch.as_tensor(loss_fn(acasXu=network)).sum()


# --- main -------------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("network", nargs="?", default="1_7", help="1_7, 1_8 or 1_9 (default 1_7)")
    parser.add_argument("--steps", type=int, default=STEPS_PER_EPOCH)
    parser.add_argument("--check", action="store_true", help="compile the specs, print losses on the start network, exit")
    parser.add_argument("--tag", default="seq", help="suffix for model and trace files (default seq)")
    parser.add_argument("--lr", type=float, default=LEARNING_RATE, help=f"Adam learning rate (default {LEARNING_RATE})")
    parser.add_argument("--reset-adam", action="store_true",
                        help="start every epoch with a fresh Adam optimiser instead of carrying its state over")
    parser.add_argument("--clip", type=float, default=None,
                        help="clip the gradient norm at this value before each step (default: no clipping)")
    parser.add_argument("--cycles", type=int, default=1,
                        help="how many times to go through the ten properties (default 1 = ten epochs)")
    args = parser.parse_args()
    net = args.network

    src = os.path.join(HERE, f"acasXu_{net}.onnx")
    models_dir = os.path.join(HERE, "models")
    traces_dir = os.path.join(HERE, "traces")

    log(f"compiling the ten one-property specifications under the {LOGIC} logic")
    losses = []
    for k, spec in enumerate(SPECS, start=1):
        started = time.time()
        losses.append(compile_loss(spec, f"property{k}"))
        log(f"  property{k:<2d} <- {os.path.relpath(spec, HERE)}  ({time.time() - started:.1f}s)")

    torch.manual_seed(SEED)
    generator = torch.Generator().manual_seed(SEED)
    whole_norm = normalise(MIN_IN + torch.rand(N_MONITOR, 5, generator=generator) * (MAX_IN - MIN_IN))

    log(f"=== network N_{{{net.replace('_', ',')}}} from {os.path.basename(src)}")
    model = load_network(src)
    check_against_onnxruntime(model, src)
    with torch.no_grad():
        original_advisories = model(whole_norm).argmin(dim=1)

    def network(x):
        return model(x.reshape(1, 5)).reshape(5)

    def all_losses():
        was_training = model.training
        model.eval()
        with torch.no_grad():
            values = [loss_value(f, network).item() for f in losses]
        if was_training:
            model.train()
        return values

    def agreement():
        with torch.no_grad():
            return float((model(whole_norm).argmin(dim=1) == original_advisories).float().mean())

    if args.check:
        log("losses and gradient norms of each property on the starting network:")
        for k, f in enumerate(losses, start=1):
            model.zero_grad()
            value = loss_value(f, network)
            value.backward()
            grad = float(torch.sqrt(sum((p.grad ** 2).sum() for p in model.parameters())))
            log(f"  property{k:<2d}: loss {value.item():+.4f}   grad norm {grad:.3e}")
        return

    os.makedirs(models_dir, exist_ok=True)
    os.makedirs(traces_dir, exist_ok=True)
    snapshot = lambda e: os.path.join(models_dir, f"acasXu_{net}_{args.tag}_e{e:02d}.onnx")  # noqa: E731

    per_epoch = open(os.path.join(traces_dir, f"{net}_{args.tag}_per_epoch.csv"), "w", newline="")
    steps_file = open(os.path.join(traces_dir, f"{net}_{args.tag}_steps.csv"), "w", newline="")
    matrix_file = open(os.path.join(traces_dir, f"{net}_{args.tag}_loss_matrix.csv"), "w", newline="")
    epoch_writer, step_writer, matrix_writer = csv.writer(per_epoch), csv.writer(steps_file), csv.writer(matrix_file)
    epoch_writer.writerow(["epoch", "trained_on", "loss_mean", "loss_last", "agreement_with_original", "seconds", "snapshot"])
    step_writer.writerow(["epoch", "trained_on", "step", "loss", "grad_norm", "seconds"])
    matrix_writer.writerow(["epoch", "trained_on"] + [f"property{k}" for k in range(1, 11)])

    start_values = all_losses()
    export(model, snapshot(0))
    epoch_writer.writerow([0, "", "", "", "1.0000", "", os.path.basename(snapshot(0))])
    matrix_writer.writerow([0, ""] + [f"{v:.6f}" for v in start_values])
    per_epoch.flush(); matrix_file.flush()
    log("epoch  0 (start): " + "  ".join(f"p{k}={v:+.3f}" for k, v in enumerate(start_values, start=1)))
    log(f"{args.cycles} x 10 epochs x {args.steps} steps, one property per epoch | {LOGIC} | alpha {ALPHA} | "
        f"Adam lr {args.lr}{' (reset every epoch)' if args.reset_adam else ''} | "
        f"gradient clipping {args.clip if args.clip is not None else 'off'}")

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    model.train()
    for epoch in range(1, 10 * args.cycles + 1):
        k = (epoch - 1) % 10 + 1          # property trained in this epoch
        if args.reset_adam and epoch > 1:
            optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
        loss_fn = losses[k - 1]
        started = time.time()
        values = []
        for step in range(1, args.steps + 1):
            step_started = time.time()
            optimizer.zero_grad()
            constraint_loss = loss_value(loss_fn, network)
            total_loss = (1 - ALPHA) * constraint_loss
            total_loss.backward()
            grad = float(torch.sqrt(sum((p.grad ** 2).sum() for p in model.parameters() if p.grad is not None)))
            if args.clip is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
            optimizer.step()
            values.append(constraint_loss.item())
            step_writer.writerow([epoch, f"property{k}", step, f"{constraint_loss.item():.6f}",
                                  f"{grad:.6f}", f"{time.time() - step_started:.2f}"])
            steps_file.flush()
            log(f"  epoch {epoch:2d} (property{k}) step {step:2d}/{args.steps}: "
                f"loss {constraint_loss.item():+.4f} | grad norm {grad:.3f}")
        seconds = time.time() - started
        model.eval()
        row = all_losses()
        agree = agreement()
        export(model, snapshot(epoch))
        model.train()
        epoch_writer.writerow([epoch, f"property{k}", f"{np.mean(values):.6f}", f"{values[-1]:.6f}",
                               f"{agree:.4f}", f"{seconds:.1f}", os.path.basename(snapshot(epoch))])
        matrix_writer.writerow([epoch, f"property{k}"] + [f"{v:.6f}" for v in row])
        per_epoch.flush(); matrix_file.flush()
        log(f"epoch {epoch:2d} (property{k}): mean {np.mean(values):+.4f} last {values[-1]:+.4f} | "
            f"agreement with original {100 * agree:.2f}% | {seconds:.0f}s | exported {os.path.basename(snapshot(epoch))}")
        log("   all ten after this epoch: " + "  ".join(f"p{k}={v:+.3f}" for k, v in enumerate(row, start=1)))

    per_epoch.close(); steps_file.close(); matrix_file.close()
    log("done")


if __name__ == "__main__":
    sys.exit(main())
