"""Split the upstream ACAS Xu specification into ten one-property TRAINING specifications.

Input:  acasXu-upstream.vcl  (vehicle-lang/vehicle, examples/acasXu/acasXu.vcl, dev branch)
Output: specs/property01.vcl ... specs/property10.vcl

Each output file is the upstream preamble (types, network, normalisation, minimalScore,
maximalScore) followed by exactly one property section and the Capucci `qllAdditive`
logic, with two changes that the loss compiler needs, both explained in the appendix of README.md:

  1. `minimalScore` and `maximalScore` lose their `i != j =>` guard and become non-strict
     (`<=` / `>=`). Under Vehicle 0.28.0 the guarded form compiles to the constant 0.
  2. the `qllAdditive` logic (capucci-logic.vcl, a local copy of the block at the end of
     chapter-code/capucci-pdt/fashionRobustness-capucci.vcl) is appended, with hardness `p`
     given on the command line.

Verification always uses acasXu-upstream.vcl itself, unchanged.

    python3 split-spec.py --p 5                 # training specs -> specs/
    python3 split-spec.py --for-verification    # verification specs -> specs-verify/
"""

import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "acasXu-upstream.vcl")
OUT = os.path.join(HERE, "specs")
CAPUCCI = os.path.join(HERE, "capucci-logic.vcl")   # the chapter's qllAdditive logic, local copy

RULE = "-" * 80


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--p", type=float, default=5.0, help="Capucci hardness (default 5.0)")
    parser.add_argument("--for-verification", action="store_true",
                        help="write specs-verify/propertyKK.vcl instead: the upstream text unchanged "
                             "(strict, guarded minimalScore/maximalScore, no logic), one property per file")
    args = parser.parse_args()
    out_dir = os.path.join(HERE, "specs-verify") if args.for_verification else OUT

    text = open(SRC).read()
    # Sections are introduced by a rule line followed by "-- Property N".
    parts = re.split(rf"(?m)^{RULE}\n(?=-- Property \d+)", text)
    preamble, sections = parts[0], parts[1:]
    assert len(sections) == 10, f"expected 10 property sections, found {len(sections)}"

    old_min = "minimalScore i x = forall j . i != j => normAcasXu x ! i < normAcasXu x ! j"
    old_max = "maximalScore i x = forall j . i != j => normAcasXu x ! i > normAcasXu x ! j"
    assert old_min in preamble and old_max in preamble
    if args.for_verification:
        note = (
            f"{RULE}\n"
            "-- VERIFICATION specification, generated by split-spec.py --for-verification from\n"
            "-- acasXu-upstream.vcl: the upstream text unchanged, restricted to one property.\n"
        )
        logic = ""
    else:
        preamble = preamble.replace(old_min, "minimalScore i x = forall j . normAcasXu x ! i <= normAcasXu x ! j")
        preamble = preamble.replace(old_max, "maximalScore i x = forall j . normAcasXu x ! i >= normAcasXu x ! j")
        note = (
        f"{RULE}\n"
        "-- TRAINING specification, generated by split-spec.py from acasXu-upstream.vcl.\n"
        "-- One property only. `minimalScore`/`maximalScore` are stated non-strictly without\n"
        "-- the `i != j` guard, because the guarded form compiles to the constant 0 under\n"
        "-- Vehicle 0.28.0's loss backend (see the appendix of README.md). The qllAdditive logic at\n"
        "-- the end is verbatim from capucci-logic.vcl (the chapter's Capucci logic)\n"
        f"-- except for p = {args.p}.\n"
    )

    if not args.for_verification:
        capucci = open(CAPUCCI).read()
        logic = capucci[capucci.index(f"{RULE}\n-- A custom differentiable logic"):]
        logic = re.sub(r"(?m)^p = 2\.0$", f"p = {args.p}", logic)
        assert f"p = {args.p}" in logic

    # Each section is the property's helper definitions followed by its `@property` block.
    # Later properties reuse earlier helpers (property2 uses intruderDistantAndSlower from
    # the Property 1 section, property4 uses directlyAhead from Property 3), so every file
    # keeps all ten sections' helper definitions and only one `@property` block.
    split_sections = []
    for section in sections:
        number = int(re.match(r"-- Property (\d+)", section).group(1))
        at = section.index("@property")
        split_sections.append((number, section[:at].rstrip("\n") + "\n", section[at:].rstrip("\n") + "\n"))

    os.makedirs(out_dir, exist_ok=True)
    for number, _, prop in split_sections:
        pieces = [note, preamble]
        for other_number, defs, other_prop in split_sections:
            pieces.append(RULE + "\n" + defs)
            if other_number == number:
                pieces.append("\n" + other_prop)
            else:
                pieces.append(f"\n-- (property{other_number} omitted from this file; see property{other_number:02d}.vcl)\n")
        if logic:
            pieces.append("\n" + logic)
        path = os.path.join(out_dir, f"property{number:02d}.vcl")
        with open(path, "w") as out:
            out.write("".join(pieces))
        print(f"wrote {os.path.relpath(path, HERE)}: {prop.splitlines()[1]}")


if __name__ == "__main__":
    main()
