name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:

env:
  PANDOC_VERSION: "3.0.1"

jobs:
  check-vehicle:
    name: Check Vehicle on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.type }}

    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: pip install -r requirements.txt
        shell: sh

      - name: Check Vehicle
        run: find . -name '*.vcl' -exec vehicle check -s {} \;
        shell: sh

    strategy:
      matrix:
        os:
          - name: Linux
            type: ubuntu-latest
          - name: macOS
            type: macos-latest
          - name: Windows
            type: windows-latest
        python:
          - version: "3.9"

  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1.0.0
        with:
          version: ${{ env.PANDOC_VERSION }}

      - name: Update README.md
        run: |
          pandoc                              \
            --defaults table-of-contents.yaml \
            --to gfm                          \
            --output README.md

      - name: Commit README.md
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md"
          file_pattern: "README.md"
