name: Update README.md

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  PANDOC_VERSION: "3.0.1"

jobs:
  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1.0.0
        with:
          version: ${{ env.PANDOC_VERSION }}

      - name: Update README.md
        run: pandoc -d .pandoc-config.yaml -t gfm -o README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README.md"
          file_pattern: "README.md"
